### ISSUE TITLE
Distribute license and tests in pypi tarball

### ISSUE THREAD

**Issue by scarabeusiv** [Zac-HD/hypothesmith#5]
For distribution purposes we need the license to be shipped with the sourcecode.
The tests would allow us to verify our python stack against the hypotesmith and see if we break up something.
Alternative option would be if you could add tags here so we would fetch the tag tarball from github.

**Comment by Zac-HD** [comment]
Hey Tomáš - awesome that you're interested.  I'm happy to bundle the license, but FYI `hypothesmith` is unlikely to find errors in Python builtins because it uses the `compile()` builtin function to correct for ambiguities in the grammar.

Fortunately this should be fixable in Python 3.9, thanks to [PEP 617](https://www.python.org/dev/peps/pep-0617/) :smile:

**Comment by jayvdb** [comment]
This issue is about packaging, especially distro packaging where the tests here are also being run on the VMs to verify that the source code is still working correctly on the openSUSE OS.

Currently the .spec in https://build.opensuse.org/package/show/devel:languages:python/python-hypothesmith is a bit messy because this repo has no tags and the PyPI sdist is not a particularly useful source distribution, especially because it doesnt include the LICENSE file which makes the sdist illegal.
